name: Build proj
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install and build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
      - name: Deploy to production
        uses: awb-pw/deploy-to-github-pages-action@1.1.1
        env:
          AUTHOR: avocadoteam
          BUILD_PATH: dist
          GITHUB_PAGE_NAME: app-sub-modal
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
          USERNAME: woophi
          EMAIL: attendentofsky@gmail.com
